spring.application.name=SpringBootLearning1

payment.provider=stripe

#debug=true

spring.datasource.url=jdbc:postgresql://localhost:5432/studentsDB
spring.datasource.username=postgres
spring.datasource.password=moloy10

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true